package org.dersbian.compiler.lexer.token;

import java.nio.file.Path;
import java.util.Objects;

/** Identifies the source. The ID is valid for the whole compilation. */
public sealed interface SourceId
        permits SourceId.FilePath,
                SourceId.VirtualResource,
                SourceId.InMemoryModule,
                SourceId.Generated {

    /** Stable textual identifier of the source. */
    String identifier();

    /** Human-readable description, useful for logs and diagnostic messages. */
    default String describe() {
        return switch (this) {
            case FilePath(var path) -> "file: " + path;
            case VirtualResource(var uri) -> "virtual: " + uri;
            case InMemoryModule(var moduleName) -> "in-memory module: " + moduleName;
            case Generated(var description) -> "generated: " + description;
        };
    }

    /** Source corresponding to a file on the filesystem. */
    record FilePath(Path path) implements SourceId {
        public FilePath {
            Objects.requireNonNull(path, "path must not be null");
        }

        @Override
        public String identifier() {
            return path.toString();
        }
    }

    /** Source of a virtual resource (URI, JAR, URL). */
    record VirtualResource(String uri) implements SourceId {
        public VirtualResource {
            Objects.requireNonNull(uri, "uri must not be null");
            if (uri.isBlank()) {
                throw new IllegalArgumentException("uri must not be blank");
            }
        }

        @Override
        public String identifier() {
            return uri;
        }
    }

    /** Source of an in-memory module (REPL, eval). */
    record InMemoryModule(String moduleName) implements SourceId {
        public InMemoryModule {
            Objects.requireNonNull(moduleName, "moduleName must not be null");
            if (moduleName.isBlank()) {
                throw new IllegalArgumentException("moduleName must not be blank");
            }
        }

        @Override
        public String identifier() {
            return moduleName;
        }
    }

    /** Source generated by the compiler (macros, etc.). */
    record Generated(String description) implements SourceId {
        public Generated {
            Objects.requireNonNull(description, "description must not be null");
            if (description.isBlank()) {
                throw new IllegalArgumentException("description must not be blank");
            }
        }

        @Override
        public String identifier() {
            return "<generated:" + description + ">";
        }
    }
}
