/*
 * This source file was generated by the Gradle 'init' task
 */

package org.dersbian;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

/** Test class for App. */
@SuppressWarnings("PMD.AtLeastOneConstructor")
class AppTest {

  @Test
  void appHasGreeting() {
    final App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
