/*
 * This source file was generated by the Gradle 'init' task
 */

package org.dersbian;

import java.io.File;
import java.util.concurrent.Callable;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import picocli.CommandLine;

/** Main application class. */
@Slf4j
@NoArgsConstructor(access = lombok.AccessLevel.PRIVATE)
@SuppressWarnings("PMD.ShortClassName")
@CommandLine.Command(
    name = "dersco",
    mixinStandardHelpOptions = true,
    version = "0.1.0",
    description = "Compilatore moderno")

public class App implements Callable<Integer> {

  /** Verbose mode flag. */
  @CommandLine.Option(
      names = {"-v", "--verbose"},
      description = "Enable verbose mode")
  private boolean verbose;

  /** Input file to process. */
  @CommandLine.Parameters(index = "0", description = "Input file")
  private File inputFile;

  /* /** Version provider. #/
  public static class Version implements CommandLine.IVersionProvider {
    @Override
    public String[] getVersion() {
      final String version = System.getProperty("app.version");
      return new String[] {version != null ? version : "unknown"};
    }
  }*/

  @Override
  public Integer call() throws Exception {
    // Logica del comando ...
    if (verbose && log.isInfoEnabled()) {
      log.info("Verbose mode attivo");
    }
    if (inputFile == null) {
      throw new CommandLine.ParameterException(new CommandLine(this), "Input file is required");
    }

    if (log.isInfoEnabled()) {
      log.info("input file: {}", inputFile.getCanonicalFile());
    }
    return 0;
  }

  /**
   * Main application entry point.
   *
   * @param args command line arguments.
   */
  @SuppressWarnings("PMD.MethodArgumentCouldBeFinal")
  public static void main(String[] args) {
    final int exitCode = new CommandLine(new App()).execute(args);
    System.exit(exitCode);
  }
}
