/*
 * This source file was generated by the Gradle 'init' task
 */

package org.dersbian;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.dersbian.cli.CliExecutionExceptionHandler;
import org.dersbian.cli.RootCommand;
// import org.fusesource.jansi.AnsiConsole;
import picocli.CommandLine;

/**
 * Application entry point.
 *
 * <p>Contains only bootstrap logic: building {@link CommandLine}, installing cross-platform ANSI
 * support (Jansi, required on Windows cmd.exe) and mapping the exit code to {@link
 * System#exit(int)}. No domain logic is present here, in keeping with the Single Responsibility
 * Principle.
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@SuppressWarnings("PMD.ShortClassName")
public final class App {

    /**
     * Application entry point.
     *
     * @param args command-line arguments.
     */
    @SuppressWarnings("PMD.MethodArgumentCouldBeFinal")
    public static void main(String[] args) {
        final int exitCode = createCommandLine().execute(args);
        System.exit(exitCode);
    }

    /**
     * Builds and configures the {@link CommandLine} instance used by the application.
     *
     * <p>Extracted into a package-private method (rather than inlined in {@code main}) to favor
     * testability: tests can obtain the same production configuration and redirect stdout/stderr
     * with {@link CommandLine#setOut} / {@link CommandLine#setErr} without calling {@link
     * System#exit(int)}.
     *
     * @return a {@link CommandLine} ready to execute.
     */
    private static CommandLine createCommandLine() {
        return new CommandLine(new RootCommand())
                .setExecutionExceptionHandler(new CliExecutionExceptionHandler())
                .setCaseInsensitiveEnumValuesAllowed(true)
                .setUsageHelpAutoWidth(true);
    }
}
