/*
 * This source file was generated by the Gradle 'init' task
 */

package org.dersbian;

import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/** Main application class. */
@Slf4j
@NoArgsConstructor
@SuppressWarnings("PMD.ShortClassName")
public class App {
  /**
   * Gets a greeting message.
   *
   * @return A greeting message.
   */
  public String getGreeting() {
    return "Hello World!";
  }

  /**
   * Main application entry point.
   *
   * @param args command line arguments.
   */
  @SuppressWarnings("PMD.MethodArgumentCouldBeFinal")
  public static void main(String[] args) {
    if (args.length > 0) {
      for (int i = 0; i < args.length; i++) {
        if (log.isInfoEnabled()) {
          log.info("arg[{}] = {}", i, args[i]);
        }
      }
    }

    if (log.isInfoEnabled()) {
      log.info(new App().getGreeting());
    }
    log.debug("Debug message");
    log.warn("Warning message");
    log.error("Error message");
  }
}
